challenge_homepage:
    path:     /
    defaults: { _controller: ChallengeBundle:Default:index }

create:
    path:     /create
    defaults: { _controller: ChallengeBundle:Challenge:create }

read:
    path:     /read
    defaults: { _controller: ChallengeBundle:Challenge:read }

update:
    path:     /update/{id}
    defaults: { _controller: ChallengeBundle:Challenge:update }

delete:
    path:     /delete/{id}
    defaults: { _controller: ChallengeBundle:Challenge:delete }

create_question:
    path:     /create_question
    defaults: { _controller: ChallengeBundle:Question:create }

read_question:
    path:     /read_question
    defaults: { _controller: ChallengeBundle:Question:read }

update_question:
    path:     /update_question/{id}
    defaults: { _controller: ChallengeBundle:Question:update }

delete_question:
    path:     /delete_question/{id}
    defaults: { _controller: ChallengeBundle:Question:delete }

qcm_question:
    path:     /qcm/{id}
    defaults: { _controller: ChallengeBundle:Question:question }

evaluation_question:
    path:     /evaluation
    defaults: { _controller: ChallengeBundle:Question:evaluation }

rechercheChallenge:
    path:     /rechercheChallenge
    defaults: { _controller: ChallengeBundle:Challenge:search }

statchallenge:
    path:     /statchallenge
    defaults: { _controller: ChallengeBundle:Challenge:statistique }

read_admin:
    path:     /readAdmin
    defaults: { _controller: ChallengeBundle:AdminChallenge:readAdmin }

create_admin:
    path:     /createAdmin
    defaults: { _controller: ChallengeBundle:AdminChallenge:createAdmin }

update_admin:
    path:     /updateAdmin/{id}
    defaults: { _controller: ChallengeBundle:AdminChallenge:updateAdmin }

delete_admin:
    path:     /deleteAdmin/{id}
    defaults: { _controller: ChallengeBundle:AdminChallenge:deleteAdmin }

statchallengeadmin:
    path:     /statchallengeadmin
    defaults: { _controller: ChallengeBundle:AdminChallenge:statistique }

create_question_admin:
    path:     /createQuestion
    defaults: { _controller: ChallengeBundle:AdminQuestion:createQuestion }

read_question_admin:
    path:     /readQuestion
    defaults: { _controller: ChallengeBundle:AdminQuestion:readQuestion }

update_question_admin:
    path:     /updateQuestion/{id}
    defaults: { _controller: ChallengeBundle:AdminQuestion:updateQuestion }

delete_question_admin:
    path:     /deleteQuestion/{id}
    defaults: { _controller: ChallengeBundle:AdminQuestion:deleteQuestion }
