<?php

namespace ChallengeBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQuestion($id){

        $qb=$this->getEntityManager()
            ->createQuery("select CONCAT(m.description,m.choix,m.reponse) AS full_name from ChallengeBundle:Question m WHERE m.id='$id'");
        return $qb->getResult();

    }
}
