<?php

namespace ChallengeBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
public function findByQuestion($id)
{
    $query=$this->getEntityManager()
        ->createQuery("SELECT m as question from ChallengeBundle:Question m where m.id ='$id' ");
    return $query->getResult();
}
    public function findByChoix()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT CONCAT(m.description,m.choix,m.reponse) as choix from ChallengeBundle:Question m ");
        return $query->getResult();
    }

}
